NOT_PAID = 'not paid'
PAID = 'paid'
PROCESSING = 'processing'
CANCELLED = 'cancelled'
WALLET_FUNDING = 'wallet funding'
WALLET_TRACKING_IDENTIFIER = 'WALLET'
PAYMENT_PENDING = 'Pending Payment'

PAYMENT_API_KEY = 'MK_TEST_UMFW43ZZH0'
PAYMENT_SECRET_KEY = 'MTXYSVDLXX62NZ9XCS8T2M1E8FYY1ZGY'
PAYMENT_URL = 'https://sandbox.monnify.com'
PAYMENT_CONTRACT_CODE = '4588107415'

COMPLETED_PAYMENT = 'Completed Payment';
PENDING_PAYMENT = 'Pending Payment';